steps:
  # 1. Build image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/winsoft-isd-cm/totwallet:latest', '.']

  # 2. Push image ke Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/winsoft-isd-cm/totwallet:latest']

  # 3. PERINTAH DARI CLOUD BUILD KE CLOUD RUN UNTUK DEPLOY AUTOMATIS!
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'totwallet'  # <-- Ubah jadi nama service Cloud Run kamu!
      - '--image=gcr.io/winsoft-isd-cm/totwallet:latest'
      - '--region=asia-southeast2'  # satu region sama VM database (instance-bukumimpi2) biar latensi rendah
      - '--port=6167'

options:
  logging: CLOUD_LOGGING_ONLY